name: kib_challenge
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  dartz: ^0.10.1
  smooth_page_indicator: ^1.2.0+3
  shimmer: ^3.0.0
  device_preview: ^1.2.0
  flutter_screenutil: ^5.9.3
  loading_animation_widget: ^1.2.1
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  dio: ^5.7.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  internet_connection_checker: ^2.0.0
  auto_route: ^9.2.2
  hive_flutter: ^1.1.0
  scrollable_table_view: ^2.0.3
  pull_to_refresh_flutter3: ^2.0.2
  fluttertoast: ^8.2.8
  flutter_dotenv: ^5.1.0

  high_q_paginated_drop_down:
    path: high_q_paginated_drop_down-2.1.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.12
  auto_route_generator: ^9.0.0
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  hive_generator: ^2.0.0
  mockito: ^5.4.4
  http_mock_adapter: ^0.6.1
  pretty_dio_logger: ^1.4.0


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - .env

