// Mocks generated by Mockito 5.4.4 from annotations
// in kib_challenge/test/core/base_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i6;
import 'package:kib_challenge/core/data_sources/api_helper/app_api_helper.dart'
    as _i4;
import 'package:kib_challenge/core/data_sources/models/base_response/base_response.dart'
    as _i2;
import 'package:kib_challenge/core/data_sources/models/pagination_model/pagination_model.dart'
    as _i3;
import 'package:kib_challenge/core/data_sources/utils/enum.dart' as _i7;
import 'package:kib_challenge/core/data_sources/utils/network/base_network_info.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseResponse_0<T1> extends _i1.SmartFake
    implements _i2.BaseResponse<T1> {
  _FakeBaseResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBasePaginationModel_1<T1> extends _i1.SmartFake
    implements _i3.BasePaginationModel<T1> {
  _FakeBasePaginationModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AppApiHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppApiHelper extends _i1.Mock implements _i4.AppApiHelper {
  MockAppApiHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.BaseResponse<T>> performPostRequest<T>({
    required String? endpoint,
    required T Function(Map<String, dynamic>)? fromJson,
    Map<String, dynamic>? data,
    Map<String, dynamic>? queryParameters,
    bool? injectToken = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performPostRequest,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #data: data,
            #queryParameters: queryParameters,
            #injectToken: injectToken,
          },
        ),
        returnValue:
            _i5.Future<_i2.BaseResponse<T>>.value(_FakeBaseResponse_0<T>(
          this,
          Invocation.method(
            #performPostRequest,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #data: data,
              #queryParameters: queryParameters,
              #injectToken: injectToken,
            },
          ),
        )),
      ) as _i5.Future<_i2.BaseResponse<T>>);

  @override
  _i5.Future<_i2.BaseResponse<T>> performPostListRequest<T>({
    required String? endpoint,
    required T Function(List<dynamic>)? fromJson,
    Map<String, dynamic>? data,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performPostListRequest,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #data: data,
            #queryParameters: queryParameters,
          },
        ),
        returnValue:
            _i5.Future<_i2.BaseResponse<T>>.value(_FakeBaseResponse_0<T>(
          this,
          Invocation.method(
            #performPostListRequest,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #data: data,
              #queryParameters: queryParameters,
            },
          ),
        )),
      ) as _i5.Future<_i2.BaseResponse<T>>);

  @override
  _i5.Future<_i2.BaseResponse<T>> performPostFormDataRequest<T>({
    required String? endpoint,
    required T Function(Map<String, dynamic>)? fromJson,
    required _i6.FormData? data,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performPostFormDataRequest,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #data: data,
            #queryParameters: queryParameters,
          },
        ),
        returnValue:
            _i5.Future<_i2.BaseResponse<T>>.value(_FakeBaseResponse_0<T>(
          this,
          Invocation.method(
            #performPostFormDataRequest,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #data: data,
              #queryParameters: queryParameters,
            },
          ),
        )),
      ) as _i5.Future<_i2.BaseResponse<T>>);

  @override
  _i5.Future<_i2.BaseResponse<T>> performPutRequest<T>({
    required String? endpoint,
    required T Function(Map<String, dynamic>)? fromJson,
    required Map<String, dynamic>? data,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performPutRequest,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #data: data,
            #queryParameters: queryParameters,
          },
        ),
        returnValue:
            _i5.Future<_i2.BaseResponse<T>>.value(_FakeBaseResponse_0<T>(
          this,
          Invocation.method(
            #performPutRequest,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #data: data,
              #queryParameters: queryParameters,
            },
          ),
        )),
      ) as _i5.Future<_i2.BaseResponse<T>>);

  @override
  _i5.Future<_i2.BaseResponse<T>> performPutFormDataRequest<T>({
    required String? endpoint,
    required T Function(Map<String, dynamic>)? fromJson,
    required _i6.FormData? data,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performPutFormDataRequest,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #data: data,
            #queryParameters: queryParameters,
          },
        ),
        returnValue:
            _i5.Future<_i2.BaseResponse<T>>.value(_FakeBaseResponse_0<T>(
          this,
          Invocation.method(
            #performPutFormDataRequest,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #data: data,
              #queryParameters: queryParameters,
            },
          ),
        )),
      ) as _i5.Future<_i2.BaseResponse<T>>);

  @override
  _i5.Future<_i2.BaseResponse<T>> performPatchFormDataRequest<T>({
    required String? endpoint,
    required T Function(Map<String, dynamic>)? fromJson,
    required _i6.FormData? data,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performPatchFormDataRequest,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #data: data,
            #queryParameters: queryParameters,
          },
        ),
        returnValue:
            _i5.Future<_i2.BaseResponse<T>>.value(_FakeBaseResponse_0<T>(
          this,
          Invocation.method(
            #performPatchFormDataRequest,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #data: data,
              #queryParameters: queryParameters,
            },
          ),
        )),
      ) as _i5.Future<_i2.BaseResponse<T>>);

  @override
  _i5.Future<_i2.BaseResponse<T>> performPatchRequestJSON<T>({
    required String? endpoint,
    required T Function(Map<String, dynamic>)? fromJson,
    Map<String, dynamic>? data,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performPatchRequestJSON,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #data: data,
            #queryParameters: queryParameters,
          },
        ),
        returnValue:
            _i5.Future<_i2.BaseResponse<T>>.value(_FakeBaseResponse_0<T>(
          this,
          Invocation.method(
            #performPatchRequestJSON,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #data: data,
              #queryParameters: queryParameters,
            },
          ),
        )),
      ) as _i5.Future<_i2.BaseResponse<T>>);

  @override
  _i5.Future<_i2.BaseResponse<T>> performDeleteRequest<T>({
    required String? endpoint,
    required T Function(Map<String, dynamic>)? fromJson,
    Map<String, dynamic>? data,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performDeleteRequest,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #data: data,
            #queryParameters: queryParameters,
          },
        ),
        returnValue:
            _i5.Future<_i2.BaseResponse<T>>.value(_FakeBaseResponse_0<T>(
          this,
          Invocation.method(
            #performDeleteRequest,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #data: data,
              #queryParameters: queryParameters,
            },
          ),
        )),
      ) as _i5.Future<_i2.BaseResponse<T>>);

  @override
  _i5.Future<_i2.BaseResponse<T>> performGetRequest<T>({
    required String? endpoint,
    required T Function(Map<String, dynamic>)? fromJson,
    Map<String, dynamic>? data,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performGetRequest,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #data: data,
            #queryParameters: queryParameters,
          },
        ),
        returnValue:
            _i5.Future<_i2.BaseResponse<T>>.value(_FakeBaseResponse_0<T>(
          this,
          Invocation.method(
            #performGetRequest,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #data: data,
              #queryParameters: queryParameters,
            },
          ),
        )),
      ) as _i5.Future<_i2.BaseResponse<T>>);

  @override
  _i5.Future<_i2.BaseResponse<T>> performGetListRequest<T>({
    required String? endpoint,
    required T Function(List<dynamic>)? fromJson,
    Map<String, dynamic>? data,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performGetListRequest,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #data: data,
            #queryParameters: queryParameters,
          },
        ),
        returnValue:
            _i5.Future<_i2.BaseResponse<T>>.value(_FakeBaseResponse_0<T>(
          this,
          Invocation.method(
            #performGetListRequest,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #data: data,
              #queryParameters: queryParameters,
            },
          ),
        )),
      ) as _i5.Future<_i2.BaseResponse<T>>);

  @override
  _i5.Future<_i3.BasePaginationModel<T>> performGetPagination<T>({
    required String? endpoint,
    required T Function(Map<String, dynamic>)? fromJson,
    required _i7.PaginationTypes? paginationTypes,
    String? listName,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #performGetPagination,
          [],
          {
            #endpoint: endpoint,
            #fromJson: fromJson,
            #paginationTypes: paginationTypes,
            #listName: listName,
            #queryParameters: queryParameters,
          },
        ),
        returnValue: _i5.Future<_i3.BasePaginationModel<T>>.value(
            _FakeBasePaginationModel_1<T>(
          this,
          Invocation.method(
            #performGetPagination,
            [],
            {
              #endpoint: endpoint,
              #fromJson: fromJson,
              #paginationTypes: paginationTypes,
              #listName: listName,
              #queryParameters: queryParameters,
            },
          ),
        )),
      ) as _i5.Future<_i3.BasePaginationModel<T>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i8.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}
